### ISSUE TITLE
添加个更新应该怎么做

### ISSUE THREAD

**Issue by kenghuo** [Longlongyu/hexo-theme-Cxo#1]
大佬, 我想给我博客添加个更新时间应该怎么做, 谢谢大佬

**Comment by Longlongyu** [comment]
抱歉- -有点不太明白你的意思，具体是怎么样的更新事件呢？

**Comment by kenghuo** [comment]
可不可以给博文添加个类似创建时间一样的更新时间, 在home页面排序方式更新时间优先级高于创建时间
