### ISSUE TITLE
指教

### ISSUE THREAD

**Issue by Freedomisgood** [Longlongyu/hexo-theme-Cxo#10]
1.如何在这一行signature: "别装作很努力,因为结局不会陪你演戏。"使这两句话分段呢?新手请指教
2.还有有什么比较好的办法显示摘要图片呢?`photos: xxx`好像显示不了.`<!--more-->的话不想让他显示在展开的全文中`
3.或者不显示摘要该怎么调整呢

**Comment by Longlongyu** [comment]
1.不行，这里的字符串是被存储进文本节点，无论换多少行都会被解析器识别成分割符。
当然你页可以修改 `\layout\includes\partial\profile.pug`：
将第十二行的
``` pug
.profile-signature=  theme.signature
```
修改为
``` pug
.profile-signature!=  theme.signature
```
最后在 `_config.yml` 修改成如下就好
``` yaml
signature: "别装作很努力<br>因为结局不会陪你演戏。"
```
2.目前不支持显示摘要图片，不过有需求就会考虑添加。
3.truncate_length 设为0即可。

**Comment by Longlongyu** [comment]
@Freedomisgood
唔，没有太好的解决方案。
能想到的只有将放置于文章顶部了

**Comment by Freedomisgood** [comment]
@Longlongyu 
行吧...
刚看了下YAML语法...关于1好像还有如下解决方法...未测试
```
signature: 别装作很努力|
 因为结局不会陪你演戏。#本行开头必须有空格
```
