### ISSUE TITLE
指教

### ISSUE THREAD

**Issue by Freedomisgood** [Longlongyu/hexo-theme-Cxo#11]
你Demo中的图片无法正常显示...
![default](https://user-images.githubusercontent.com/31088082/44955445-1c946b00-aee6-11e8-995f-c5c477820cd3.jpg)
我想加个公众号的二维码进去....这边该怎么操作呢?
![2](https://user-images.githubusercontent.com/31088082/44955535-6e89c080-aee7-11e8-938f-230245be8811.jpg)
我在content: 后面加了Markdown语法显然是不行的,后来在---options---后面加了markdown的图片,但是想了想有layout应该不行吧.....试着加了一下这个也失败了
```
photos:
- https://raw.githubusercontent.com/Freedomisgood/Freedomisgood.github.io/master/about/%E4%BA%8C%E7%BB%B4%E7%A0%81.jpg
```

**Comment by Longlongyu** [comment]
你将二维码图放到主题根目录的source\img文件夹下
然后这样就可以了
`![二维码](/img/二维码.jpg)`
记得前后回车隔开。
网站的图片无法正常显示，应该是因为图片是谷歌上直接粘的链接，被墙了。
