### ISSUE TITLE
请问评论插件为何不能起作用？

### ISSUE THREAD

**Issue by YBFJ** [Longlongyu/hexo-theme-Cxo#12]
你好，我看到你的设置里有coment，引入了一些插件，但是为什么没有起作用呢？

**Comment by YBFJ** [comment]
你太厉害了，好像加上来必应的账号uid就可以了，建议加上怎么开启评论界面这个章节？

**Comment by Longlongyu** [comment]
😉 好的，会在Wiki中补充这部分的内容！！！
