### ISSUE TITLE
文字高亮语法支持问题

### ISSUE THREAD

**Issue by superman285** [Longlongyu/hexo-theme-Cxo#15]
请问下大大，目前不支持文字高亮语法"=="，怎么修改代码或配置可以让他支持呢？

**Comment by Longlongyu** [comment]
不好意思。这么晚才回复。

语法高亮，需要markdown代码块语法首行```后加对应语言

如  ``` js 开头
中间加入 对应code
就会有对应的语法高亮了

![802bb7450aea6d9c583b1ce48cde964](https://user-images.githubusercontent.com/40429255/46324201-de918080-c624-11e8-90fd-dc5845a89bf0.png)

具体细节可以去看相关文档。

**Comment by superman285** [comment]
谢谢你的回答哈。语法高亮明白了，其实想问的是typora里头的==文字高亮==哈，不过估计是typora自带的功能，不是md原生支持的。
