### ISSUE TITLE
您好，我该如何添加一个音乐播放器

### ISSUE THREAD

**Issue by guanru** [Longlongyu/hexo-theme-Cxo#19]

**Comment by Longlongyu** [comment]
因为最近暂时没有时间管理项目的原因，所以如果想添加音乐播放器的话，就需要对该主题进行二次开发了，可以去选择使用一些成熟的音乐播放器插件。

**Comment by guanru** [comment]
我在底部添加了一个网易云外链，没有很好看，总算能用，新手菜鸟，有问题会向您请教，感谢~
