### ISSUE TITLE
想要自己在body处加入一个背景的js文件需要修改什么地方

### ISSUE THREAD

**Issue by PassingFoam** [Longlongyu/hexo-theme-Cxo#2]
![image](https://user-images.githubusercontent.com/41845204/43363659-8a593b86-933c-11e8-8cb0-822ff1e3007a.png)
就是在这里背景处加入动态的背景js，并应用到每个页面
![image](https://user-images.githubusercontent.com/41845204/43363668-ada18e36-933c-11e8-9918-b8702acaaa7d.png)
感谢大佬

**Comment by Longlongyu** [comment]
嗯，能否提供此类效果的js文件或链接吗？

**Comment by Longlongyu** [comment]
你可能需要 Cxo 目录下的 layout/includes 文件夹下 layout.pug 的进行修改。
在那里修改内联样式和引入 js 文件。
如果修改幅度较大可能需要 `npm install` 所需依赖，进行2次开发。

**Comment by PassingFoam** [comment]
[https://github.com/hustcc/canvas-nest.js/](url)
好的，我去看看，对pug不是很了解，流泪
