### ISSUE TITLE
[提议]：主页头部背景图片增加属性background-position: center;

### ISSUE THREAD

**Issue by zhujinyao822** [Longlongyu/hexo-theme-Cxo#22]
文件定位是这个：Cxo\layout\includes\partial\header.pug
行号是第18行

```pug
- let bgStyle =  `background-image: url(${bgURL});background-position:center;`
```

增加了`background-position: center;`后不用担心调整浏览器时图片视口会固定在图片的某个地方，导致体验没那么好。

**Comment by Longlongyu** [comment]
收到意见并进行修改了。:smile:
