### ISSUE TITLE
Latex公式支持

### ISSUE THREAD

**Issue by Freedomisgood** [Longlongyu/hexo-theme-Cxo#38]
请问以后能支持latex嘛，从大一开始用该Theme，非常喜欢，现在需要开始书写点公式了
用其他主题尝试了下Markdown it Plus渲染器
[如何在HEXO中渲染Latex数学公式](https://blog.csdn.net/u014792304/article/details/78687859)文中提到：
在博客html的head中加载Katex的CSS样式 
这一步可以手动做，但是每次hexo clean后还得手动一次很麻烦；因为hexo是基于模板生成html文件，所以可以将样式表写入模板中。 
以默认主题landscape为例。在路径/themes/landscape/layout/_partial下找到head.ejs文件，将以下语句写入文件中即可
<link href="https://cdn.bootcss.com/KaTeX/0.7.1/katex.min.css" rel="stylesheet">,
针对Cxo不知需要修改哪边

**Comment by stevenjoezhang** [comment]
可以装插件： https://github.com/stevenjoezhang/hexo-filter-mathjax
不需要修改其它任何内容，不需要任何前端脚本。

**Comment by GoogleGu** [comment]
> 可以装插件： https://github.com/stevenjoezhang/hexo-filter-mathjax
> 不需要修改其它任何内容，不需要任何前端脚本。

厉害了老哥

**Comment by Freedomisgood** [comment]
> 可以装插件： https://github.com/stevenjoezhang/hexo-filter-mathjax
> 不需要修改其它任何内容，不需要任何前端脚本。

that's cool!

**Comment by Freedomisgood** [comment]
> 可以装插件： https://github.com/stevenjoezhang/hexo-filter-mathjax
> 不需要修改其它任何内容，不需要任何前端脚本。

That's cool!
