### ISSUE TITLE
代码区块 显示top异常？

### ISSUE THREAD

**Issue by linwenbang** [Longlongyu/hexo-theme-Cxo#5]
![image](https://user-images.githubusercontent.com/11420716/44699072-1c930600-aab5-11e8-80d8-71d6108fc762.png)

chrome浏览器

**Comment by Longlongyu** [comment]
如果是你想在代码区块中显示标题，应该使用以下语法：
```
{% codeblock [title] [lang:language] [url] [link text] %}
code snippet
{% endcodeblock %}
```

例如：
```
{% codeblock Hello.js lang:js %}
alert('Hello World!');
{% endcodeblock %}
```

效果如下：
![2ojl d7 e396c0 40973d0s](https://user-images.githubusercontent.com/40429255/44705367-05faa800-aad1-11e8-9ceb-d1f7ef258bee.png)

**Comment by linwenbang** [comment]
如果是不想要这个标题栏呢？




| |
文邦
邮箱：linwenbang@yeah.net
|

签名由 网易邮箱大师 定制

在2018年08月28日 23:17，Mr.Long 写道：

Closed #5.
