### ISSUE TITLE
关于访问次数，加入更多统计的支持

### ISSUE THREAD

**Issue by liuyib** [Longlongyu/hexo-theme-Cxo#8]
刷新一次网页访问次数就会加一，这不太好吧？应该得设置一个时间间隔吧？

**Comment by Longlongyu** [comment]
这个是引入**不蒜子**统计的。不过会考虑加入对其他统计的支持的，这样选择面会更多。

**Comment by YBFJ** [comment]
你好厉害啊！！！才学了这么久就弄出来好多东西啊，我也是要转前端，不过是生物狗转前端，和你一比我的进度好慢，，像你学习~博客用你的主题啦~写写你~
